### ISSUE TITLE
Limit number of messages handled in time to reduce number of workflows scheduled

### ISSUE THREAD

**Issue by pacospace** [thoth-station/investigator#155]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pacospace** [comment]
@KPostOffice can we add an environment variable `THOTH_NUMBER_MESSAGES_PROCESSED` per minute or per hour that is converted accordingly as discussed in chat with the solution you proposed?

**Comment by KPostOffice** [comment]
If we can query argo to check the number of currently running workflows I think it might be more effective to pass a `stop` and `start` threshold.

**Comment by fridex** [comment]
> `stop` and `start` threshold.

What would `stop` and `start` do? Maybe I'm missing the `start` meaning here. (I would expect just upper limit to stop scheduling workflows).

**Comment by KPostOffice** [comment]
I was thinking that there might be issues with starting and stopping to often, having a lower threshold for starting will let us schedule continuously for a period of time.

**Comment by KPostOffice** [comment]
I talked it through with someone, I don't think it matters. The check is going to be made no matter what and when the consumers are sitting in the loop there is no other work they could be doing.  The only issue I see is the delay in the request to the Argo REST API.  We may get an issue where we go over whatever threshold we set when all consumers believe that the number of workflows has dropped below the threshold.

We could solve this in one of two ways in my opinion:
* set our limit to be a reasonable amount lower to account for this
* create a service which handles all the consumers requests sequentially and responds with whether or not the consumer is allowed to schedule more workflows.

**Comment by fridex** [comment]
> I talked it through with someone, I don't think it matters. The check is going to be made no matter what and when the consumers are sitting in the loop there is no other work they could be doing. The only issue I see is the delay in the request to the Argo REST API. We may get an issue where we go over whatever threshold we set when all consumers believe that the number of workflows has dropped below the threshold.
> 
> We could solve this in one of two ways in my opinion:
> 
> * set our limit to be a reasonable amount lower to account for this
> * create a service which handles all the consumers requests sequentially and responds with whether or not the consumer is allowed to schedule more workflows.

I think having just one configuration option (e.g. in configmap or supplied as an environment variable to investigator) should work. Investigator is the component that schedules workflows so it can have control of it. Producers can produce messages which will be processed later on (kafka will keep the messages).

**Comment by KPostOffice** [comment]
A configmap would be better because we have more than just investigator scheduling new workflows.  We could maybe add this functionality to thoth-common. Like have some argument `limit`, and if it is set then before scheduling it will check and see if the total number of workflows is less than the limit.

**Comment by pacospace** [comment]
Solved by https://github.com/thoth-station/investigator/pull/215
