### ISSUE TITLE
Investigator Takes Care of All Consumer Logic

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/investigator#170]
Move all faust consumers into a single app. This will cut down on the number of metrics pages we will have to scrape and the number of pods that we have running as well as ensuring that any consumer config applies to all message being processed.

TODO:
- [x] package-update-consumer
- [x] package-releases-consumer
- [x] advise-update-consumer
- [x] adviser-reporter-consumer

**Comment by KPostOffice** [comment]
Accidentally added too many consumers to move here it's only `package-update-consumer` and `advise-reporter-consumer`

**Comment by KPostOffice** [comment]
This will be closed by #175

**Comment by pacospace** [comment]
Fixed by @KPostOffice
