### ISSUE TITLE
Create logic to handle SI UnanalyzedPackageMessage

### ISSUE THREAD

**Issue by pacospace** [thoth-station/investigator#204]
**Is your feature request related to a problem? Please describe.**
graph-refresh producer send different messages to Kafka that need to be handled by investigator.

**Describe the solution you'd like**
Make sure Investigator is able to consumer all messages  from graph-refresh and schedule workflows accordingly.

**Describe alternatives you've considered**

**Additional context**

**Comment by pacospace** [comment]
Reference: https://github.com/thoth-station/investigator#dev-guide

**Comment by saisankargochhayat** [comment]
https://github.com/thoth-station/graph-refresh-job/issues/457#issuecomment-676128893
What's the best way to check if si-result exist for a particular package, version, index URL before scheduling a si-workflow?

**Comment by pacospace** [comment]
I think no because you are using the query to database to retrieve unanalyzed already :) so for sure it should not be there :)
