### ISSUE TITLE
Enforce First Come First Serve

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/investigator#272]
**Is your feature request related to a problem? Please describe.**
Workflows wait without knowing the order in which they came, we have no guarantee the execution will occur in order of arrival

**Describe the solution you'd like**
Add a queue which takes a function and its arguments and will schedule a workflow or batches of workflows when within the proper limits.

**Describe alternatives you've considered**
- Leave as is.
- Go one step further and use a priority queue which will allow us to differentiate when it comes to message importance.  User triggered messages blocking advises can have `HIGH` priority

**Comment by KPostOffice** [comment]
We can basically just have:

```python
while true:
  free = limit - get_pending_workflows
  for i in range(free):
    to_run = queue.dequeue():
    to_run[0](**to_run[1])
  await sleep(sleep_time)
```

**Comment by KPostOffice** [comment]
WDYT? @fridex @goern

**Comment by fridex** [comment]
> WDYT? @fridex @goern

Sounds like a reasonable step. Is this handled by Kafka automatically on the messaging side?

**Comment by KPostOffice** [comment]
@fridex This would be implemented by us in investigator. The only issue I see coming up is the queue growing to large we should probably use some sort of persistent queue so that we don't have to store it in mem.  I think Faust would allow us to define some sort of internal channel

**Comment by KPostOffice** [comment]
Or we could find some other queue implementation

**Comment by fridex** [comment]
It's not clear to me why this is needed on investigator side. Does it consume all the messages at once? Can be the message consumption balanced?

**Comment by KPostOffice** [comment]
We could limit the queue size and have consumers wait if the queue is full but then we will run into the same problem where we can't ensure that the first message to arrive will be the first added to the queue.

**Comment by fridex** [comment]
> We could limit the queue size and have consumers wait if the queue is full but then we will run into the same problem where we can't ensure that the first message to arrive will be the first added to the queue.

Could you point me to the sources where this is happening? I'm not sure if I understand this correctly. My assumption is that investigator consumes a message and processes it. The queueing part is left on Kafka. Having another queue implemented in the middle of a message broker and message consumer does not feel right to me.

**Comment by KPostOffice** [comment]
https://github.com/thoth-station/investigator/blob/4d0db6b335c5e4fe1abf6a406720a7e0dfaf053e/investigator/investigator/common.py#L75

Anywhere we await for limit if we have multiple waiting we have no way of guaranteeing fcfs, if A starts waiting before B but when B arrives the number of workflows is below the limit it will be scheduled before A.  Once limit is reached scheduling order is mostly random other than when many workflows finish at once, then we'll probably unblock all at about the same time

**Comment by fridex** [comment]
So as discussed today on the call, we will be redesigning this. Let's write it up after tomorrow's tech talk.

**Comment by goern** [comment]
@KPostOffice @fridex what is the state of this? Please put a priority, project and lifecycle on it ;)

/kind feature

**Comment by KPostOffice** [comment]
I think this can be closed
