### ISSUE TITLE
Create docs for this module

### ISSUE THREAD

**Issue by fridex** [thoth-station/investigator#287]
**Is your feature request related to a problem? Please describe.**

Let's create documentation for this module so that it is available at https://thoth-station.ninja/docs/ and from the main page https://thoth-station.ninja/

**Comment by pacospace** [comment]
Do we need to add in `docs/source` all the content in `.rst` format to be available automatically?

**Comment by fridex** [comment]
> Do we need to add in `docs/source` all the content in `.rst` format to be available automatically?

Yes, sphinx expects rst.
