### ISSUE TITLE
Improve workflow limits for scheduling workflows

### ISSUE THREAD

**Issue by pacospace** [thoth-station/investigator#311]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by goern** [comment]
/assign @pacospace 
/hold

what do we want to do here?

#refinement-required

**Comment by pacospace** [comment]
> /assign @pacospace
> /hold
> 
> what do we want to do here?
> 
> #refinement-required

We just look at the pending workflows currently to keep investigator scheduling under control, but we should consider total workflows, because the cluster has a limit on the total number of workflow objects that can be created

Example:

PENDING_WORKFLOW_LIMIT = 1000 
cluster workflow objects limit = 1000

 The cluster considers all type of workflow objects, not just pending, therefore when we set the limit considering only pending workflow, we might end up losing workflows.

@harshad16 WDYT? I think we discussed once this problem in a call. @KPostOffice WDYT?

**Comment by fridex** [comment]
> > /assign @pacospace
> > /hold
> > what do we want to do here?
> > #refinement-required
> 
> We just look at the pending workflows currently to keep investigator scheduling under control, but we should consider total workflows, because the cluster has a limit on the total number of workflow objects that can be created
> 
> Example:
> 
> PENDING_WORKFLOW_LIMIT = 1000
> cluster workflow objects limit = 1000
> 
> The cluster considers all type of workflow objects, not just pending, therefore when we set the limit considering only pending workflow, we might end up losing workflows.
> 
> @harshad16 WDYT? I think we discussed once this problem in a call. @KPostOffice WDYT?

What issue are you trying to solve here? The pending workflow limit was introduced not to create too many workflows at the same time.

**Comment by fridex** [comment]
Is this still relevant?

**Comment by pacospace** [comment]
I think we can close it, as the method that was used at the time as changed now in investigator.
