### ISSUE TITLE
Move investigator to thoth namespace

### ISSUE THREAD

**Issue by fridex** [thoth-station/investigator#343]
**Describe the bug**

I tried to generate docs for investigator using sphinx and nepthys. It fails as investigator does not use namespace `thoth`:

```
/home/fpokorny/git/thoth-station/nepthys/clones/investigator/thoth is not a directory.
```

**To Reproduce**

```
sphinx-apidoc -o docs/source thoth --implicit-namespaces
```

**Expected behavior**

Investigator should be moved to thoth namespace. As of now, all the sources live in `investigator/investigator`, we should rather use `thoth/investigator`.

**Comment by pacospace** [comment]
> **Describe the bug**
> 
> I tried to generate docs for investigator using sphinx and nepthys. It fails as investigator does not use namespace `thoth`:
> 
> ```
> /home/fpokorny/git/thoth-station/nepthys/clones/investigator/thoth is not a directory.
> ```
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> ```
> sphinx-apidoc -o docs/source thoth --implicit-namespaces
> ```
> 
> **Expected behavior**
> 
> Investigator should be moved to thoth namespace. As of now, all the sources live in `investigator/investigator`, we should rather use `thoth/investigator`.

I think we moved to `investigator/investigator` because there was some issue with imports, but I understand the problem @KPostOffice WDYT?

**Comment by fridex** [comment]
Done in the linked PR #361.
