### ISSUE TITLE
investigator is having trouble scheduling adviser and kebechet workflows

### ISSUE THREAD

**Issue by harshad16** [thoth-station/investigator#383]
**Describe the bug**

Investigator is unable to scheduling data processing workflows adviser and kebechet in stage. 
It gives out the following error message in its log (without debug mode on) 
`parse_kebechet_trigger_message() got an unexpected keyword argument 'graph'"`

**Additional context**

Investigator version : v0.6.0

**Comment by pacospace** [comment]
@KPostOffice is investigator expecting each method to have graph and openshift in their specific consumer methods?

**Comment by KPostOffice** [comment]
Closed with new release of investigator `v0.6.1`
