### ISSUE TITLE
Do we want to keep maintaining message content in README files?

### ISSUE THREAD

**Issue by fridex** [thoth-station/investigator#394]
**Describe the question**

Following documentation in investigator, there are stated what fields are present in the message, see for example:

https://github.com/thoth-station/investigator/blob/f54d94b/thoth/investigator/adviser_trigger/README.md

Is this something we want to provide and maintain the README file? It looks to me this is redundant and having a link to the message content present in messaging could be sufficient enough for this.

**Comment by pacospace** [comment]
> **Describe the question**
> 
> Following documentation in investigator, there are stated what fields are present in the message, see for example:
> 
> https://github.com/thoth-station/investigator/blob/f54d94b/thoth/investigator/adviser_trigger/README.md
> 
> Is this something we want to provide and maintain the README file? It looks to me this is redundant and having a link to the message content present in messaging could be sufficient enough for this.

It seems redundant as you said indeed. The link to the message structure in thoth-station/messaging is definitely enough.

Also if the message change in the messaging library we do not need to modify the README in investigator.

Thanks @fridex!

**Comment by KPostOffice** [comment]
One reason to keep it is to document the contents of all supported versions of each message. If we have handlers for `v1`, `v2`, and `v3` it might be nice to update the README with the specific contents of each version.  Linking to messaging would only get `v3`.

**Comment by fridex** [comment]
> One reason to keep it is to document the contents of all supported versions of each message. If we have handlers for `v1`, `v2`, and `v3` it might be nice to update the README with the specific contents of each version. Linking to messaging would only get `v3`.

That makes sense :+1: Do we want to track it using GitHub URLs to commit/PRs with changes done not to commit code in README in that case?

**Comment by KPostOffice** [comment]
Yeah that makes sense. I will update all the READMEs.  Each will always have an item, `current`, which is associated with the most recent commit to `master`

**Comment by fridex** [comment]
Fixed in #409, thanks @KPostOffice.
