### ISSUE TITLE
KeyError  crashlooping the prod investigator

### ISSUE THREAD

**Issue by harshad16** [thoth-station/investigator#479]
**Describe the bug**

investigator is running to crashloop with following error:
```
Traceback (most recent call last):
  File "consumer.py", line 235, in _confluent_consumer_loop
    func = _handler_lookup(msg.topic(), v)
  File "consumer.py", line 120, in _handler_lookup
    return table[topic_name][version]
KeyError: 'v1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "consumer.py", line 289, in <module>
    loop.run_until_complete(asyncio.gather(*tasks))
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "consumer.py", line 238, in _confluent_consumer_loop
    "No handler for version %s of %s", v, _get_class_from_topic_name(msg.topic_name())
AttributeError: 'cimpl.Message' object has no attribute 'topic_name'
```

**Details**
Investigator: v0.10.1
Messaging: v0.10.3

**To Reproduce**
1. Go to 'https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/thoth-infra-prod/pods'
2. Click on 'investigator-consumer' pod
3. Scroll down to logs

**Expected behavior**
investigator running successfully

**Comment by harshad16** [comment]
this seems like issue of consumer ahead of producer 

the messaging version v0.10.3: https://github.com/thoth-station/messaging/blob/493a16b3a736bf72fc4f919daa8ad80efd584a14/thoth/messaging/adviser_re_run.py#L53
various investigator is at v0.10.1: https://github.com/thoth-station/investigator/blob/21a58618aaab9186519704becde8e4dac55fff9d/thoth/investigator/adviser_re_run/investigate_adviser_re_run.py#L38

**Comment by harshad16** [comment]
same for 
https://github.com/thoth-station/investigator/blob/v0.10.1/thoth/investigator/adviser_trigger/investigate_adviser_trigger.py
https://github.com/thoth-station/messaging/blob/v0.10.3/thoth/messaging/adviser_trigger.py

**Comment by harshad16** [comment]
same for 
https://github.com/thoth-station/investigator/blob/21a58618aaab9186519704becde8e4dac55fff9d/thoth/investigator/provenance_checker_trigger/investigate_provenance_checker_trigger.py#L37
https://github.com/thoth-station/messaging/blob/493a16b3a736bf72fc4f919daa8ad80efd584a14/thoth/messaging/provenance_checker_trigger.py#L47

**Comment by harshad16** [comment]
All these component uses send-messages workflow which submits message through messaging-cli
which is causing the issue.

**Comment by fridex** [comment]
The issue still persists:

```
  queue = asyncio.Queue(maxsize=Configuration.NUM_WORKERS, loop=loop)  # type: asyncio.Queue
Traceback (most recent call last):
  File "consumer.py", line 235, in _confluent_consumer_loop
    func = _handler_lookup(msg.topic(), v)
  File "consumer.py", line 120, in _handler_lookup
    return table[topic_name][version]
KeyError: 'v4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "consumer.py", line 289, in <module>
    loop.run_until_complete(asyncio.gather(*tasks))
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "consumer.py", line 238, in _confluent_consumer_loop
    "No handler for version %s of %s", v, _get_class_from_topic_name(msg.topic_name())
AttributeError: 'cimpl.Message' object has no attribute 'topic_name'
```

**Comment by KPostOffice** [comment]
https://github.com/thoth-station/investigator/blob/63bfe13144fc095cecb1a596308be4f8edea4b60/thoth/investigator/adviser_trigger/investigate_adviser_trigger.py#L37

**Comment by harshad16** [comment]
This was fixed with the referenced PR's
Thanks everyone for the efforts.
closing the issue.
