### ISSUE TITLE
KEBECHET_SLUG not defined in kebechet template.

### ISSUE THREAD

**Issue by harshad16** [thoth-station/investigator#496]
**Describe the bug**
```
Requested to assign parameter 'KEBECHET_SLUG' (value None) to template but template does not provide the given parameter, forcing
`````
it is set here https://github.com/thoth-station/common/blob/1a6d581159f3b4b38e121324dfb4cbbe246d4a6c/thoth/common/openshift.py#L1539
https://github.com/thoth-station/common/blob/1a6d581159f3b4b38e121324dfb4cbbe246d4a6c/thoth/common/workflows.py#L642

not defined in here: https://github.com/thoth-station/thoth-application/blob/master/kebechet/base/openshift-templates/kebechet.yaml

**Comment by harshad16** [comment]
cc: @KPostOffice

**Comment by KPostOffice** [comment]
This is dependent on: https://github.com/thoth-station/workflow-helpers/pull/223
