### ISSUE TITLE
Modify Adviser Workflow and create kafka producer and consumer for unsolved packages from adviser run [8pt]

### ISSUE THREAD

**Issue by goern** [thoth-station/investigator#50]
As Thoth User
I would like to receive justifications regarding missing advice on my software stack due to missing dependencies solved in Thoth Knowledge Graph. I would like to know also when I will receive my advised software stacks.

**Goal**
Improve user experience when we have unsolved software stacks.

**References**
- https://docs.google.com/document/d/1dLUccuLR8khRSQz1hyWxuZpaStKcfSRZdYzK56D2juA/edit#heading=h.tct8a7owp4ue
- https://docs.google.com/document/d/1tKjdOpxMgemmKQk9laXjPfHa50IIDdi2udDn5YBsUaU/edit#heading=h.lo5bxjjl8jea

seeAlso https://trello.com/c/Gct0cGSQ/951-8-modify-adviser-workflow-and-create-kafka-producer-and-consumer-for-unsolved-packages-from-adviser-run-nokr

**Comment by pacospace** [comment]
```
solver-rhel-8-py36-9f5b33cf         Running     21s   21s        0
test-investigator-6btbz             Succeeded   50s   28s        0
```
Test succeeded, after sending an UnresolvedPackageMessage, investigator consumer scheduled solver for the package identified in adviser results.
