### ISSUE TITLE
Should we have an alarm on paused messages?

### ISSUE THREAD

**Issue by pacospace** [thoth-station/investigator#552]

**Comment by pacospace** [comment]
Related-To: https://github.com/thoth-station/thoth-application/issues/854

**Comment by KPostOffice** [comment]
I think this is a good idea, I can also change the name from `paused` to `halted` to better illustrate the severity. WDYT?

**Comment by pacospace** [comment]
> I think this is a good idea, I can also change the name from `paused` to `halted` to better illustrate the severity. WDYT?

Let's do it: created a separate issue for that, PTAL: https://github.com/thoth-station/investigator/issues/558
