### ISSUE TITLE
Perform ack on fail only on specific messages

### ISSUE THREAD

**Issue by pacospace** [thoth-station/investigator#554]
**Is your feature request related to a problem? Please describe.**
I would like to use ack on fail only on specific messages

**Describe the solution you'd like**
Perform ack on fail only on specific messages

**Describe alternatives you've considered**

**Additional context**
Related-To: https://github.com/thoth-station/investigator/issues/551

**Comment by KPostOffice** [comment]
Whew. Got there eventually
