### ISSUE TITLE
Rename message from paused to halted for alarms

### ISSUE THREAD

**Issue by pacospace** [thoth-station/investigator#558]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
See: https://github.com/thoth-station/investigator/issues/552#issuecomment-876691807

**Comment by pacospace** [comment]
Related-To: https://github.com/thoth-station/thoth-application/issues/854

**Comment by KPostOffice** [comment]
closed with #559
