### ISSUE TITLE
Expose offset metric for messages

### ISSUE THREAD

**Issue by pacospace** [thoth-station/investigator#582]
**Is your feature request related to a problem? Please describe.**
As Thoth Maintainer,

I want to have an alarm when messages are not consumed.

**Describe the solution you'd like**
Expose offset metric for messages

**Describe alternatives you've considered**

**Additional context**
https://github.com/thoth-station/thoth-application/issues/854

**Comment by pacospace** [comment]
@KPostOffice did we already implement this metric?

**Comment by KPostOffice** [comment]
Yes, closed by https://github.com/thoth-station/investigator/pull/583
/close

**Comment by pacospace** [comment]
> Yes, closed by #583 /close

Thanks @KPostOffice
