### ISSUE TITLE
Use investigator to reschedule adviser run [8pt]

### ISSUE THREAD

**Issue by pacospace** [thoth-station/investigator#63]
Use investigator to reschedule adviser run when all missing unresolved packages have been solved [8pt]

Pre-requisite:
- [x] Modify messaging CLI to accept json file with List of Dict containing THOTH_MESSAGING_TOPIC_NAME and THOTH_MESSAGING_MESSAGE_CONTENTS (https://github.com/thoth-station/messaging/issues/211)

Tasks:

- [x] Create AdviserReRunMessage in thoth-messaging containing info about adviser re run (https://github.com/thoth-station/messaging/pull/207);
- [x] create query in storage to get adviser ids that need to be re run with unresolved package list (https://github.com/thoth-station/storages/pull/1959);
- [x] Add method in workflow helper to define adviser that needs to be re run based on solved packages and output them (https://github.com/thoth-station/workflow-helpers/pull/44)
- [x] Add task to solver workflow with parse_solved_package from workflow-helpers (https://github.com/thoth-station/thoth-application/pull/399)
- [x] Add task in solver to send AdviserReRunMessage (https://github.com/thoth-station/thoth-application/pull/399)
- [x] Add `parse_adviser_re_run` message method in investigator (https://github.com/thoth-station/investigator/pull/192)

**Comment by KPostOffice** [comment]
The blog post:
https://developers.redhat.com/blog/?p=812617&preview=true

**Comment by fridex** [comment]
Is this still relevant or should we close this?

**Comment by pacospace** [comment]
I cannot see the blog post on red hat developers, any links @KPostOffice ? Otherwise we can close it from my side

**Comment by pacospace** [comment]
@KPostOffice is working on a blog for kafka, we can close this issue.
