### ISSUE TITLE
Use multiple consumer based on different topics

### ISSUE THREAD

**Issue by harshad16** [thoth-station/investigator#673]
**Is your feature request related to a problem? Please describe.**

Currently, one consumer is being used in investigator, which works with our current functionality.
However as our data ingestion is growing date-to-date, we should split the topic of data ingestion and data services 
between multiple consumers to handle them. This way users wouldn't be kept on a long hold.

**Acceptance criteria** 
- [ ] Explore to way to implement multiple consumer via confluent in investigator. 
- [ ] create different consumers for data ingestion and data services topics.
- [ ] Verify it works.

**Comment by harshad16** [comment]
- Consumer could be blocking due to namespaces, as right now it will limit based namespace workflow limit.
The thought is to have consumers based on namespace. 

consumer - namespace - topics
------------------------------------------  
c1 -> middletier -> subscribe to only topic of middletier 
c2 -> backend -> subscribe to only topic of backend

**Comment by KPostOffice** [comment]
I think it would be good to split the function lookup table into two new ones, one for middletier and one for backend and make the default behavior to run both functions to ensure no breaking in compatibility with old deployment configurations.
